const fs = require('fs').promises,
    path = require('path'),
    exif = require('fast-exif'),
    got = require('got'),
    IMAGE_EXTENSIONS = ['jpeg', 'jpg', 'png'],
    Feed = require('feed').Feed;

const feed = new Feed({
    title: 'Lands Upon',
    description: 'A photo blog of the lands that @arpitbatra123 has walked upon',
    id: 'https://lands-upon.vercel.app/',
    link: 'https://lands-upon.vercel.app/',
    language: 'en',
    image: 'https://lands-upon.vercel.app/og.jpg',
    favicon: 'https://lands-upon.vercel.app/favicon.ico',
    feedLinks: {
        rss: 'https://lands-upon.vercel.app/feed.xml',
    },
    author: {
        name: 'Arpit Batra',
        email: 'arpitbatra123@gmail.com',
    }
});

// https://stackoverflow.com/questions/1140189/converting-latitude-and-longitude-to-decimal-values
function ConvertDMSToDD(direction, degrees, minutes, seconds) {
    var dd = degrees + minutes / 60 + seconds / (60 * 60);

    if (direction == 'S' || direction == 'W') {
        dd = dd * -1;
    } // Don't do anything for N or E
    return dd;
}

function processLocationInfo(file, tags) {
    if (!tags || !tags.gps || !tags.gps.GPSLatitudeRef) {
        console.log(`${file} has no gps info available`);
        return;
    }

    const gps = {
        latitude: ConvertDMSToDD(tags.gps.GPSLatitudeRef, ...tags.gps.GPSLatitude),
        longitude: ConvertDMSToDD(tags.gps.GPSLongitudeRef, ...tags.gps.GPSLongitude)
    };

    return gps;
}

async function getLocationName(gps) {
    const response = await got(
        `https://api.mapbox.com/geocoding/v5/mapbox.places/${gps.longitude},${gps.latitude}.json?access_token=pk.eyJ1IjoiYXJwaXRiYXRyYTEyMyIsImEiOiJja2Q2N3ViMGkwbzgzMnFuem55NG10OHNqIn0.zoeIkNpnI16a6Vz69A1UCA`
    ).json();

    return response.features[1].place_name;
}

async function generateFeed() {
    let files = await fs.readdir(path.resolve('assets/images'));

    // Making sure only images are processed, autogenerated files like .DS_Store are ignored
    files = files.filter((file) => {
        const extension = file.split('.')[1];
        return IMAGE_EXTENSIONS.includes(extension.toLocaleLowerCase());
    });

    files = files.map(async (file) => {
        const tags = await exif.read(path.resolve(`assets/images/${file}`));
        const gps = processLocationInfo(file, tags);
        const date = tags && tags.exif && new Date(tags.exif.DateTimeOriginal);

        if (gps) {
            const name = await getLocationName(gps);
            const formattedDate = date ? date.toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
            }) : 'Unknown Date';
            
            return {
                title: `${name} - ${formattedDate}`,
                id: `https://lands-upon.vercel.app/${file}`,
                link: `https://lands-upon.vercel.app/#${file}`,
                date: date,
                content: `<img src='https://lands-upon.vercel.app/assets/images/${file}' alt='${name}' style='max-width: 100%; height: auto;'>`,
                description: `<img src='https://lands-upon.vercel.app/assets/images/${file}' alt='${name}' style='max-width: 100%; height: auto;'>`
            };
        }
        
        return null;
    });

    let finalData = await Promise.all(files);
    finalData = finalData.filter((item) => item !== null).sort((a, b) => a.date.getTime() - b.date.getTime());
    
    // Add items to feed in chronological order
    finalData.forEach(item => {
        feed.addItem({
            title: item.title,
            id: item.id,
            link: item.link,
            date: new Date(item.date),
            content: item.content,
            description: item.description
        });
    });
    
    // Write the feed to the _site directory
    await fs.writeFile(path.resolve('_site/feed.xml'), feed.rss2());
    console.log('Feed generated successfully');
}

generateFeed().catch(console.error);
