/**
 * RSS Feed generator - optimized to use shared utilities
 * Modified by AI Assistant to eliminate code duplication and add caching
 * @https://cursor.com/
 */

const fs = require('fs').promises,
    path = require('path'),
    exif = require('fast-exif'),
    IMAGE_EXTENSIONS = ['jpeg', 'jpg', 'png'],
    Feed = require('feed').Feed,
    { getLocationName, processLocationInfo } = require('./_data/utils');

const feed = new Feed({
    title: 'Lands Upon',
    description: 'A photo blog of the lands that @arpitbatra123 has walked upon',
    id: 'https://lands-upon.vercel.app/',
    link: 'https://lands-upon.vercel.app/',
    language: 'en',
    image: 'https://lands-upon.vercel.app/og.jpg',
    favicon: 'https://lands-upon.vercel.app/favicon.ico',
    feedLinks: {
        rss: 'https://lands-upon.vercel.app/feed.xml',
    },
    author: {
        name: 'Arpit Batra',
        email: 'arpitbatra123@gmail.com',
        link: 'https://arpit.tk'
    }
});


async function generateFeed() {
    let files = await fs.readdir(path.resolve('assets/images'));

    // Making sure only images are processed, autogenerated files like .DS_Store are ignored
    files = files.filter((file) => {
        const extension = file.split('.')[1];
        return IMAGE_EXTENSIONS.includes(extension.toLocaleLowerCase());
    });

    files = files.map(async (file) => {
        const tags = await exif.read(path.resolve(`assets/images/${file}`));
        const gps = processLocationInfo(file, tags);
        const date = tags && tags.exif && new Date(tags.exif.DateTimeOriginal);

        if (gps) {
            const name = await getLocationName(gps);
            const formattedDate = date ? date.toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
            }) : 'Unknown Date';
            
            return {
                title: `${name} - ${formattedDate}`,
                id: `https://lands-upon.vercel.app/${file}`,
                link: `https://lands-upon.vercel.app/#${file}`,
                date: date,
                content: `<img src='https://lands-upon.vercel.app/assets/images/${file}' alt='${name}' style='max-width: 100%; height: auto;'>`,
                description: `<img src='https://lands-upon.vercel.app/assets/images/${file}' alt='${name}' style='max-width: 100%; height: auto;'>`
            };
        }
        
        return null;
    });

    let finalData = await Promise.all(files);
    finalData = finalData.filter((item) => item !== null).sort((a, b) => a.date.getTime() - b.date.getTime());
    
    // Add items to feed in chronological order
    finalData.forEach(item => {
        feed.addItem({
            title: item.title,
            id: item.id,
            link: item.link,
            date: new Date(item.date),
            content: item.content,
            description: item.description
        });
    });
    
    // Write the feed to the _site directory
    await fs.writeFile(path.resolve('_site/feed.xml'), feed.rss2());
    console.log('Feed generated successfully');
}

generateFeed().catch(console.error);
