/**
 * Stats data file - optimized to use shared utilities
 * Modified by AI Assistant to eliminate code duplication and add caching
 * @https://cursor.com/
 */

const fs = require('fs').promises,
    path = require('path'),
    exif = require('fast-exif'),
    IMAGE_EXTENSIONS = ['jpeg', 'jpg', 'png'],
    { getLocationName, processLocationInfo } = require('./utils');

module.exports = async function getStats() {
    let files = await fs.readdir(path.resolve('assets/images'));

    // Making sure only images are processed, autogenerated files like .DS_Store are ignored
    files = files.filter((file) => {
        const extension = file.split('.')[1];
        return IMAGE_EXTENSIONS.includes(extension.toLocaleLowerCase());
    });

    files = files.map(async (file) => {
        const tags = await exif.read(path.resolve(`assets/images/${file}`));
        const gps = processLocationInfo(file, tags);
        const date = tags && tags.exif && new Date(tags.exif.DateTimeOriginal);

        let name;
        if (gps) {
            name = await getLocationName(gps);
        }

        return {
            file,
            gps,
            name,
            date,
        };
    });

    let finalData = await Promise.all(files);
    finalData = finalData.filter((item) => item.gps).sort((a, b) => a.date.getTime() - b.date.getTime());
    
    // Calculate stats
    const stats = {
        totalPhotos: finalData.length,
        uniqueLocations: new Set(finalData.map(item => item.name)).size,
        dateRange: finalData.length > 0 ? {
            earliest: finalData[0].date,
            latest: finalData[finalData.length - 1].date
        } : null,
        countries: new Set(finalData.map(item => {
            // Extract country from location name (usually the last part)
            const parts = item.name.split(', ');
            return parts[parts.length - 1];
        })).size
    };
    
    return stats;
};
